routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function () {

    //Módulo creacion de usuarios
    Route::get('/usuario', 'RegistrarAjaxController@registrar');
    Route::resource('registrarAjax', 'RegistrarAjaxController');

});

app/Device.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Device extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'platform', 'platform_version', 'browser', 'browser_version', 'is_desktop', 'is_mobile', 'language', 'is_trusted', 'is_unstrusted'
    ];

    protected $table = 'devices';

    // Relación
    public function usuario()
    {
        return $this->belongsTo('App\User','user_id');
    }  

}

app/Login.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Login extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'ip_address', 'type', 'user_id', 'device_id'
    ];

    protected $table = 'logins';

    // Relación
    public function usuario()
    {
        return $this->belongsTo('App\User','user_id');
    }  

    public function device()
    {
        return $this->belongsTo('App\Device','device_id');
    }

}

app/Registro.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Registro extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $table = 'users';


}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Lab404\AuthChecker\Models\HasLoginsAndDevices;
use Lab404\AuthChecker\Interfaces\HasLoginsAndDevicesInterface;

class User extends Authenticatable implements HasLoginsAndDevicesInterface
{
    use Notifiable, HasLoginsAndDevices;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

        // Relación
    public function login()
    {
        return $this->hasMany('App\Login','user_id');
    }    

    public function device()
    {
        return $this->hasMany('App\Device','device_id');
    }  
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/RegistrarAjaxController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\User;

class RegistrarAjaxController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function registrar()
    {
        return view('usuario');
    }

    public function index(Request $request)

    {

        $users = User::latest()->paginate(5);

        return response()->json($users);

    }

    public function store(Request $request)

    {
        $user = new User;
        $user->name = $request->get('name');
        $user->email = $request->get('email'); 
        $user->password = bcrypt($request->get('password'));
        
        if ($user->save()){
            $result = true;
        }else{
            $result = false;
        }

        return response()->json($result);

    }

    public function update(Request $request, $id)

    {

        $user = User::find($id);

        $user->name = $request->get('name');
        $user->email = $request->get('email'); 
        if($user->password != $request->password){
            $user->password = bcrypt($request->get('password'));
        }else{
            $user->password = $request->password; 
        }
        
        if($user->update()){
            $result = true;
        }else{
            $result = false;
        }


        return response()->json($result);

    }

    public function destroy($id)

    {

        User::find($id)->delete();

        return response()->json(['done']);

    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="row">
            @if(Auth::user()->rol == "admin")
                <div class="col-lg-12 col-md-12">
                    <div class="card">
                        <div class="card-header" data-background-color="orange">
                            <h4 class="title">Log</h4>
                            <p class="category">Último acceso de los usuarios</p>
                        </div>
                        <div class="card-content">
                            @foreach($logins as $login)
                                <div class="col-lg-6 col-md-6 col-sm-6">
                                    <div class="card card-stats">
                                        <div class="card-header" data-background-color="blue">
                                            Preguntas contestadas: {{ $login['count'] }} 
                                        </div>
                                        <div class="card-content">
                                            <p class="category"><strong>Usuario:</strong> <span class="text-success">{{ $login->usuario->name }}</span></p>
                                            <p class="category"><strong>Acceso:</strong> <span class="text-success">{{ $login->created_at }}</span></p>
                                            <p class="category"><strong>Plataforma:</strong> <span class="text-success">{{ $login->device['platform'] }}</span></p>
                                            <p class="category"><strong>Modulo:</strong><span class="text-success"> {{ $login->modulo_name }}</span></p>
                                        </div>
                                    </div>

                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            @endif
            @if(Auth::user()->rol == "invitado")
                <div class="col-lg-5 col-md-6 col-sm-6">
                    <div class="card card-stats">
                        <div class="card-header" data-background-color="blue">
                            {{$result1}} %
                        </div>
                        <div class="card-content">
                            <p class="category">Total</p>
                            <p class="category"><span class="text-success">Tuviste {{$countModulo1}} aciertos de {{$totalPreguntasModulo1}} preguntas.</span></p>
                        </div>
                        <div class="card-footer">
                            <div class="stats">
                                <p><i class="material-icons">update</i> <a href="/questionario/1">Accede a Importancia de la Seguridad de la Información.</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-6">
                    <div class="card card-stats">
                        <div class="card-header" data-background-color="purple">
                            {{$result2}} %
                        </div>
                        <div class="card-content">
                            <p class="category">Total</p>
                            <p class="category"><span class="text-success">Tuviste {{$countModulo2}} aciertos de {{$totalPreguntasModulo2}} preguntas.</span></p>
                        </div>
                        <div class="card-footer">
                            <div class="stats">
                                <p><i class="material-icons">update</i> <a href="/questionario/2">Accede a Bases de Seguridad de la Información.</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-6">
                    <div class="card card-stats">
                        <div class="card-header" data-background-color="green">
                            {{$result3}} %
                        </div>
                        <div class="card-content">
                            <p class="category">Total</p>
                            <p class="category"><span class="text-success">Tuviste {{$countModulo3}} aciertos de {{$totalPreguntasModulo3}} preguntas.</span></p>
                        </div>
                        <div class="card-footer">
                            <div class="stats">
                                <p><i class="material-icons">update</i> <a href="/questionario/3">Accede a Principales Amenazas y Riesgos.</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-6">
                    <div class="card card-stats">
                        <div class="card-header" data-background-color="orange">
                            {{$result4}} %
                        </div>
                        <div class="card-content">
                            <p class="category">Total</p>
                            <p class="category"><span class="text-success">Tuviste {{$countModulo4}} aciertos de {{$totalPreguntasModulo4}} preguntas.</span></p>
                        </div>
                        <div class="card-footer">
                            <div class="stats">
                                <p><i class="material-icons">update</i> <a href="/questionario/4">Accede a Medidas preventivas de seguridad de información.</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-6">
                    <div class="card card-stats">
                        <div class="card-header" data-background-color="red">
                            {{$result5}} %
                        </div>
                        <div class="card-content">
                            <p class="category">Total</p>
                            <p class="category"><span class="text-success">Tuviste {{$countModulo5}} aciertos de {{$totalPreguntasModulo5}} preguntas.</span></p>
                        </div>
                        <div class="card-footer">
                            <div class="stats">
                                <p><i class="material-icons">update</i> <a href="/questionario/5">Accede a Escenarios de riesgo de seguridad de información.</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>
@push('scripts')
@endpush
@endsection

resources/views/layouts/app_back.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/modulo.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header" data-background-color="orange">
                        <h4 class="title">Crear Módulo</h4>
						<p class="category">Completa los campos</p>
                    </div>
                    <div class="card-content">
						<div class="row">
							<div class="col-lg-12 margin-tb">
								<div class="pull-right">
									<button type="button" class="btn btn-success" data-toggle="modal" data-target="#create-item">Crear Módulo</button>
						        </div>
						    </div>
						</div>
						<table class="table table-bordered table-hover">
							<thead>
							    <tr>
				        			<th>Nombre</th>
				        			<th>Descripción</th>
				        			<th>Cantidad de Preguntas</th>
				        			<th>Action</th>
			        			</tr>
							</thead>
							<tbody>
							</tbody>
						</table>
						<ul id="pagination" class="pagination-sm"></ul>
					    <!-- Create Item Modal -->
						<div class="modal fade" id="create-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
							<div class="modal-dialog" role="document">
						    	<div class="modal-content">
						    		<div class="modal-header">
						    			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
						    			<h4 class="modal-title" id="myModalLabel">Crear Módulo</h4>
								    </div>
						      		<div class="modal-body">
							      		<form data-toggle="validator" action="{{ route('moduloAjax.store') }}" method="POST">
							      			<div class="form-group">
												<label class="control-label" for="title">Nombre:</label>
												<input type="text" name="nombre" class="form-control" data-error="Please enter name." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Descripción:</label>
												<input type="text" name="description" class="form-control" data-error="Please enter Description." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Número de Preguntas:</label>
												<input type="text" name="cantidad_preguntas" class="form-control" data-error="Please enter Número de Preguntas." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<button type="submit" class="btn crud-submit btn-success">Enviar</button>
											</div>
							      		</form>
					      			</div>
						    	</div>
						  	</div>
						</div>
						<!-- Edit Item Modal -->
						<div class="modal fade" id="edit-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
							<div class="modal-dialog" role="document">
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
										<h4 class="modal-title" id="myModalLabel">Editar Módulo</h4>
							      	</div>
							      	<div class="modal-body">
							      		<form data-toggle="validator" action="/moduloAjax/14" method="put">
							      			<div class="form-group">
							      				<label class="control-label" for="title">Nombre:</label>
												<input type="text" name="nombre" class="form-control" data-error="Please enter Name." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Descripción:</label>
												<input type="text" name="description" class="form-control" data-error="Please enter description." required/>
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Número de Preguntas:</label>
												<input type="text" name="cantidad_preguntas" class="form-control" data-error="Please enter Número de Preguntas." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<button type="submit" class="btn btn-success crud-submit-edit">Guardar</button>
											</div>
							      		</form>
							      	</div>
							    </div>
						    </div>
					    </div>
				    </div>
			    </div>
		    </div>
		</div>
	</div>
</div>
@push('scripts')
<script type="text/javascript">

   var url = "<?php echo route('moduloAjax.index')?>";

</script>
<script src="/js/modulo-ajax.js"></script>
@endpush
@endsection

resources/views/pregunta.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header" data-background-color="orange">
                        <h4 class="title">Crear Preguntas</h4>
						<p class="category">Completa los campos</p>
                    </div>
                    <div class="card-content">
						<div class="row">
							<div class="col-lg-12 margin-tb">
								<div class="pull-right">
									<button type="button" class="btn btn-success" data-toggle="modal" data-target="#create-item">Crear Preguntas</button>
						        </div>
						    </div>
						</div>
						<table class="table table-bordered table-hover">
							<thead>
							    <tr>
				        			<th>Módulo</th>
				        			<th>Pregunta</th>
				        			<th>Orden</th>
				        			<th>Action</th>
			        			</tr>
							</thead>
							<tbody>
							</tbody>
						</table>
						<ul id="pagination" class="pagination-sm"></ul>
					    <!-- Create Item Modal -->
						<div class="modal fade" id="create-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
							<div class="modal-dialog" role="document">
						    	<div class="modal-content">
						    		<div class="modal-header">
						    			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
						    			<h4 class="modal-title" id="myModalLabel">Crear Preguntas</h4>
								    </div>
						      		<div class="modal-body">
							      		<form data-toggle="validator" action="{{ route('preguntaAjax.store') }}" method="POST">
							      			<div class="form-group">
												<label class="control-label" for="title">Módulo:</label>
												<select id="selectModulo" name="modulo_id" class="form-control" data-error="Please enter name." required></select>
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Pregunta:</label>
												<textarea class="form-control" data-error="Please enter Pregunta." name="pregunta" rows="3" required></textarea>
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Orden:</label>
												<input type="text" name="orden" class="form-control" data-error="Please enter Orden." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<button type="submit" class="btn crud-submit btn-success">Enviar</button>
											</div>
							      		</form>
					      			</div>
						    	</div>
						  	</div>
						</div>
						<!-- Edit Item Modal -->
						<div class="modal fade" id="edit-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
							<div class="modal-dialog" role="document">
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
										<h4 class="modal-title" id="myModalLabel">Editar Módulo</h4>
							      	</div>
							      	<div class="modal-body">
							      		<form data-toggle="validator" action="/preguntaAjax/14" method="put">
							      			<div class="form-group">
							      				<label class="control-label" for="title">Módulo:</label>
												<select id="selectModuloEditar" name="modulo_id" class="form-control" data-error="Please enter name." required></select>
												
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Pregunta:</label>
												<textarea class="form-control" data-error="Please enter Pregunta." name="pregunta" rows="3" required></textarea>
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Orden:</label>
												<input type="text" name="orden" class="form-control" data-error="Please enter Orden." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<button type="submit" class="btn btn-success crud-submit-edit">Guardar</button>
											</div>
							      		</form>
							      	</div>
							    </div>
						    </div>
					    </div>
				    </div>
			    </div>
		    </div>
		</div>
	</div>
</div>
@push('scripts')
<script type="text/javascript">

   var url = "<?php echo route('preguntaAjax.index')?>";

</script>
<script src="/js/pregunta-ajax.js"></script>
@endpush
@endsection

resources/views/usuario.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<div class="card-header" data-background-color="orange">
                        <h4 class="title">Crear Usuario</h4>
						<p class="category">Completa los campos</p>
                    </div>
                    <div class="card-content">
						<div class="row">
							<div class="col-lg-12 margin-tb">
								<div class="pull-right">
									<button type="button" class="btn btn-success" data-toggle="modal" data-target="#create-item">Crear usuario</button>
						        </div>
						    </div>
						</div>
						<table class="table table-bordered">
							<thead>
							    <tr>
				        			<th>Nombre</th>
				        			<th>Email</th>
				        			<th width="200px">Action</th>
			        			</tr>
							</thead>
							<tbody>
							</tbody>
						</table>
						<ul id="pagination" class="pagination-sm"></ul>
					    <!-- Create Item Modal -->
						<div class="modal fade" id="create-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
							<div class="modal-dialog" role="document">
						    	<div class="modal-content">
						    		<div class="modal-header">
						    			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
						    			<h4 class="modal-title" id="myModalLabel">Crear Usuario</h4>
								    </div>
						      		<div class="modal-body">
							      		<form data-toggle="validator" action="{{ route('registrarAjax.store') }}" method="POST">
							      			<div class="form-group">
												<label class="control-label" for="title">Nombre:</label>
												<input type="text" name="name" class="form-control" data-error="Please enter name." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Email:</label>
												<input type="text" name="email" class="form-control" data-error="Please enter email." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Password:</label>
												<input type="password" name="password" class="form-control" data-error="Please enter password." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<button type="submit" class="btn crud-submit btn-success">Enviar</button>
											</div>
							      		</form>
					      			</div>
						    	</div>
						  	</div>
						</div>
						<!-- Edit Item Modal -->
						<div class="modal fade" id="edit-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
							<div class="modal-dialog" role="document">
								<div class="modal-content">
									<div class="modal-header">
										<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
										<h4 class="modal-title" id="myModalLabel">Editar Usuario</h4>
							      	</div>
							      	<div class="modal-body">
							      		<form data-toggle="validator" action="/registrarAjax/14" method="put">
							      			<div class="form-group">
							      				<label class="control-label" for="title">Nombre:</label>
												<input type="text" name="name" class="form-control" data-error="Please enter Name." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Email:</label>
												<input type="text" name="email" class="form-control" data-error="Please enter description." required/>
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<label class="control-label" for="title">Password:</label>
												<input type="password" name="password" class="form-control" data-error="Please enter password." required />
												<div class="help-block with-errors"></div>
											</div>
											<div class="form-group">
												<button type="submit" class="btn btn-success crud-submit-edit">Guardar</button>
											</div>
							      		</form>
							      	</div>
							    </div>
						    </div>
					    </div>
				    </div>
			    </div>
		    </div>
		</div>
	</div>
</div>
@push('scripts')
<script type="text/javascript">

   var url = "<?php echo route('registrarAjax.index')?>";

</script>
<script src="/js/item-ajax.js"></script>
@endpush
@endsection

resources/views/video.blade.php
@extends('layouts.app')

@section('content')
<div class="content">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				<div class="card">
					<a href="http://www.youtube.com/watch?v=k6mFF3VmVAs" data-toggle="lightbox" data-gallery="youtubevideos" class="col-sm-4">
					    <img src="//i1.ytimg.com/vi/yP11r5n5RNg/mqdefault.jpg" class="img-fluid">
					</a>
					<a href="http://youtu.be/iQ4D273C7Ac" data-toggle="lightbox" data-gallery="youtubevideos" class="col-sm-4">
					    <img src="//i1.ytimg.com/vi/iQ4D273C7Ac/mqdefault.jpg" class="img-fluid">
					</a>
					<a href="//www.youtube.com/embed/b0jqPvpn3sY" data-toggle="lightbox" data-gallery="youtubevideos" class="col-sm-4">
					    <img src="//i1.ytimg.com/vi/b0jqPvpn3sY/mqdefault.jpg" class="img-fluid">
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
@push('scripts')
<script type="text/javascript">
	$(document).on('click', '[data-toggle="lightbox"]', function(event) {
	    event.preventDefault();
	    $(this).ekkoLightbox();
	});
</script>
@endpush
@endsection